discourse_salesforce:
  salesforce_enabled:
    default: false
  salesforce_login_enabled:
    default: false
    client: true
    validator: 'SalesforceLoginEnabledValidator'
  salesforce_client_id:
    default: ''
    client: true
  salesforce_client_secret:
    default: ''
    secret: true
  salesforce_rsa_private_key:
    default: ''
    textarea: true
  salesforce_authorization_server_url:
    default: 'https://login.salesforce.com'
  salesforce_username:
    default: ''
  salesforce_case_tag_name:
    default: 'salesforce-case'
  salesforce_case_status_tag_enabled:
    default: true
  salesforce_case_status_tag_prefix:
    default: 'case'
  salesforce_instance_url:
    default: ''
    client: true
    hidden: true
  salesforce_max_feed_items_per_day:
    default: -1
    min: -1
  salesforce_leads_group_id:
    default: ''
    hidden: true
  salesforce_contacts_group_id:
    default: ''
    hidden: true
  salesforce_automatic_case_sync_tags:
    type: tag_list
    client: true
    default: ""
  salesforce_case_origin:
    default: 'Web'
  salesforce_skip_contact_creation_on_case_sync:
    default: false
  salesforce_default_contact_id_for_case_sync:
    default: ""
  salesforce_api_error_logs:
    default: false
    hidden: true
  salesforce_auth_verbose_logging:
    default: false
